### ISSUE TITLE
Add support for custom language modes?

### ISSUE THREAD

**Issue by infctr** [dotcypress/vscode-console-log#1]
First of all thanks for the neat extension I got to know while I was still on SublimeText!

https://github.com/dotcypress/vscode-console-log/commit/325083830d2baf46d3e1bc3eb6fe4834699400ef#diff-06f1274e40de25abda72d812b1cce86aR39

Last update matches `editor.document.languageId` strictly to `javascript` or `rust`. There was no language check before that, so the extension worked on my setup where I use `javascriptreact` language setting for my js files.

Is there a possibility to add custom languages via settings, or add a default case for language id switch statement mb?

**Comment by dotcypress** [comment]
Hey @infctr 

Support for `javascriptreact` landed in `v0.6.1`

**Comment by infctr** [comment]
Many thanks for that!
